---
- hosts: word2vec
  become: yes
  become_user: hadoop
  tasks:
    - name: setup hdfs folders
      command: "{{ item }} chdir=/opt/word2vec/crawldb"
      with_items:
      - /opt/hadoop/bin/hdfs dfs -rmr /word2vec
      - /opt/hadoop/bin/hdfs dfs -mkdir /word2vec
      - /opt/hadoop/bin/hdfs dfs -mkdir /word2vec/crawldb
      - /opt/hadoop/bin/hdfs dfs -put /opt/word2vec/crawldb/sachin-tendulkar.txt /word2vec/crawldb/
      become: yes
      become_user: hadoop
      become_method: sudo
      environment:
    - debug: var=ansible_default_ipv4.address
    - name: run spark job
      command: /opt/word2vec/data_process/create-word2vec-model.sh
      environment:
        PYTHONPATH: $SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.9-src.zip:$PYTHONPATH

