---
- hosts: word2vec
  become: yes
  become_user: hadoop
  tasks:
    - name: Download WordPress
      get_url: url=http://d3kbcqa49mib13.cloudfront.net/spark-2.1.0-bin-hadoop2.6.tgz dest=/opt/spark-2.1.0-bin-hadoop2.6.tgz
      become: yes
      become_user: root
    - name: Extract archive
      unarchive: src=/opt/spark-2.1.0-bin-hadoop2.6.tgz
                 dest=/opt
                 copy=no
      become: yes
      become_user: root
    - name: creat soft link
      command: bash -lc "cd /opt && unlink spark && ln -s /opt/spark-2.1.0-bin-hadoop2.6 spark"
      become: yes
      become_user: root
    #- name: Install list of apt packages
    #  apt: name={{item}} state=installed
    #  with_items:
    #    - python-dev
    #    - python-pip
    #  become: yes
    #  become_user: root
    #- name: install python packages 
    #  command: pip install -r /opt/word2vec/requirements.txt
    #  become: yes
    #  become_user: root
    #- name: install pyspark 
    #  command: bash -lc "cd /opt/spark/python && pip install -e ."
    #  become: yes
    #  become_user: root
#    - debug: var=ansible_default_ipv4.address
#    - name: run spark job
#      command: /opt/word2vec/data_process/create-word2vec-model.sh
#      environment:
#        PYTHONPATH: $SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.9-src.zip:$PYTHONPATH
#  - name: Install pip ignoring "install-recommends"
#    apt:
#      name: python-pip
#      install_recommends: no
#  - name: clone repo
#    git: >
#      repo=https://github.com/cloudmesh/cloudmesh.word2vec.git
#      update=no
#      dest=/tmp/word2vec
#      version=add_ansible_deployment_ag
#      accept_hostkey=yes
#  - name: Copy word2vec code
#    command: cp -R /tmp/word2vec/code /opt/word2vec 
#  - name: creates model folder
#    file: path=/opt/word2vec/model state=directory
#  - name: creates crawldb folder
#    file: path=/opt/word2vec/crawldb state=directory
#  - name: install packages 
#    command: pip install -r /opt/word2vec/requirements.txt
#  - name: Fix 'word2vec' permissions
#    file: path=/opt/word2vec owner=hadoop group=hadoop mode=0775 state=directory recurse=yes
#  - name: crawl pages 
#    command: python /opt/word2vec/crawler/wikicrawl.py

